### ISSUE TITLE
columns selected here miss the column HADM_ID ?

### ISSUE THREAD

**Issue by inseptember** [bvanaken/clinical-outcome-prediction#10]
https://github.com/bvanaken/clinical-outcome-prediction/blob/b376f4bcd72d6d8da40078b416fb8e926ca22ba9/tasks/adm_dis_match_mimic/adm_dis_match_mimic.py#L108

**Comment by inseptember** [comment]
And how to pretrain the wiki before the diag task?

**Comment by bvanaken** [comment]
Hi,
since these notes are only used for the pre-training task, we don't necessarily need the HADM_ID column here. Or did you find that there is an issue with the column missing?

For pre-training on WIKI data, you can first create the data via [adm_dis_match_wiki.py](https://github.com/bvanaken/clinical-outcome-prediction/blob/master/tasks/adm_dis_match_wiki/adm_dis_match_wiki.py) and then use the resulting data set for outcome pre-training via [outcome_pretraining.py](https://github.com/bvanaken/clinical-outcome-prediction/blob/master/experiments/outcome_pretraining.py).

Hope this is helpful!
Best regards
Betty
